version: "3.8"
services:
  summarizer:
    build:
      context: .
      args:
        PRELOAD_MODEL: "true"   # set to "false" for a smaller image + first-run download
    environment:
      SUMM_MODEL: facebook/bart-large-cnn
      GRADIO_SERVER_NAME: 0.0.0.0
      GRADIO_SERVER_PORT: 7860
      HF_HOME: /data/hf
    ports:
      - "7860:7860"
    volumes:
      - hf_cache:/data/hf   # persist Hugging Face cache across runs
volumes:
  hf_cache:
